### ISSUE TITLE
Check for existence of S3 bucket

### ISSUE THREAD

**Issue by MRSchexnayder** [lfagan/Amazon-AWS-NAnt-Tasks#1]
This is not so much a bug because your solution works exactly as written. I would, however, like to ask for the following enhancement: be able to specify a sub-directory of the bucket being used to upload the file.

In essence: s3://[bucket]/[path]/[file]

Currently your solution only allows: s3://[bucket]/[file]

Maybe allow the "BucketName" to contain the full path needed but the "DoesBucketExist()" routine could include another variable that truncates the name if it contains '/' characters. 

Another solution would be to allow another attribute that contains the sub-directory path that gets concatenated during the upload

I wish I knew C# enough to do this myself, because I have have a hunch this isn't going to be difficult to do to an experienced developer.   

For now, I've simply commented out the calls to "DoesBucketExist()" and it seems to work fine. 

Thanks! 
Micheal Schexnayder

**Comment by armandomiani** [comment]
Now you can upload to a bucket using this: 

<amazon-s3
            accesskey="${access.key}"

```
        secretkey="${secret.key}"
        bucket="s3-gaia-application-drive"

        file="${gaia.dir}/gaia-release.zip"
        key="old-releases/gaia-release-${build.date}.zip"


        overwrite="true"
    />
```

file refers to the sourcefile. Where in the disk your source file is stored.
key refers to the destination. Where in S3 your file will be stored.

Let me know if this solves your issue.

Thanks,

Armando

**Comment by MRSchexnayder** [comment]
Should have closed this awhile ago. :)
